### ISSUE TITLE
Use Java 16 to build mincraft 1.17

### ISSUE THREAD

**Issue by brandonmcclure** [sindastra-docker/build-spigotmc#1]
With the new [1.17 spigot builds](https://www.spigotmc.org/threads/spigot-bungeecord-1-17.510208/) we need to use java 16 or later to build/run it. The docker image needs to be updated to openjdk16 to allow it to build for this version

**Comment by sindastra-docker** [comment]
- [x] Created legacy branch
- [x] Created :legacy tag on Docker Hub
- [x] Merged
- [x] Updated Readme(s)
- [x] Updated GitHub actions to build Spigot 1.17

From now on, there's the main/master branch (:latest Docker tag) and the legacy branch (:legacy Docker tag).

The images on Docker Hub should build automatically. Enjoy!

PS Here's the GitHub action, where you can see the main/master branch successfully building 1.16.5 and 1.17: https://github.com/sindastra-docker/build-spigotmc/runs/2815387175
